on:
  push:
    branches: [ "Implement-releasing" ]

env:
  CARGO_TERM_COLOR: always
  
jobs:
  build:
    name: Release Nightly Snapshot
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: |
          echo "{date}={$(date +'%Y-%m-%d')}" >> $GITHUB_STATE
      - name: Checkout master Branch
        uses: actions/checkout@v2
        with:
          ref: 'Implement-releasing'
      - name: Build
        run: cargo build --verbose
      - name: Create Release
        id: nightly-snapshot
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: tag-${{ env.date }}
          RELEASE_NAME: release-${{ env.date }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: ${{ env.RELEASE_NAME }}
          draft: false
          prerelease: false
